backend:
  name: git-gateway
  branch: main  # Change to your main branch name

media_folder: "images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"

collections:
  - name: "posts"  # The collection name
    label: "Blog Posts"
    folder: "content/posts"  # The folder where blog posts are stored
    create: true
    slug: "{{slug}}"  # URL slug format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
